name: Build and Deploy

on:
  release:
    types: [released]
  workflow_dispatch:

env:
  DOWNLOAD_RELEASE_TEMP_PATH: ${{ github.workspace }}/modloader-temp
  #  MODLOADER_HTML_FILENAME: "Degrees of Lewdity VERSION.html.mod-polyfill.html"
  I18NMOD_FILENAME: "ModI18N.mod.zip"

  MODLOADER_HTML_NORMAL_FILENAME: "Degrees of Lewdity VERSION.html.mod.html"
  MODLOADER_HTML_POLYFILL_FILENAME: "Degrees of Lewdity VERSION.html.mod-polyfill.html"

  MANIFEST_JSON_NORMAL_FILENAME: "manifest-normal.json"
  MANIFEST_JSON_POLYFILL_FILENAME: "manifest-polyfill.json"

  UPLOAD_ARTIFACT_NAME: "ModLoader-Artifact"
  UPLOAD_ARTIFACT_FILEPATH: ${{ github.workspace }}/Modloader-Artifact.zip

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Directories
        run: |
          mkdir -p "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/mods"

      - id: getI18NRelease
        name: Download I18N Mod
        uses: robinraju/release-downloader@v1
        with:
          repository: "NumberSir/DoL-I18n-Build"
          latest: true
          fileName: "ModI18N-*.mod.zip"

      - id: getModLoaderRelease
        name: Download ModLoader Build
        uses: robinraju/release-downloader@v1
        with:
          repository: "Lyoko-Jeremie/DoLModLoaderBuild"
          latest: true
          fileName: "DoL-ModLoader-*.zip"

      - name: Extract Modloader Build
        run: |
          unzip -q ${{ fromJson(steps.getModLoaderRelease.outputs.downloaded_files)[0] }} -d ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}

      - name: Create Remote Mod Loading env
        run: |
          echo '["mods/${{ env.I18NMOD_FILENAME }}"]' > "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/modList.json"
          mv "${{ fromJson(steps.getI18NRelease.outputs.downloaded_files)[0] }}" "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/mods/${{ env.I18NMOD_FILENAME }}"

      - name: Construct PWA
        run: |
          cp -r .github/pwa/* ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}

      - name: Modify HTML
        shell: python3 {0}
        run: |
          for html_name, manifest_name in zip(
            ["${{ env.MODLOADER_HTML_NORMAL_FILENAME }}", "${{ env.MODLOADER_HTML_POLYFILL_FILENAME }}"],
            ["${{ env.MANIFEST_JSON_NORMAL_FILENAME }}", "${{ env.MANIFEST_JSON_POLYFILL_FILENAME }}"]
          ):
            with open(f"${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/{html_name}", "r+", encoding="utf-8") as index_html_file:
              index_html = index_html_file.read()
              insert_index = index_html.find('<meta charset="UTF-8" />')
              index_html = index_html[:insert_index] + \
                  f"<link rel=\"manifest\" href=\"{manifest_name}\">\n" + index_html[insert_index:]
              insert_index = index_html.find('<body>\n\t<div id="init-screen">') + 7
              index_html = index_html[:insert_index] + \
                  "    <script>\n" + \
                  "        if (typeof navigator.serviceWorker !== 'undefined') {\n" + \
                  "            navigator.serviceWorker.register('sw.js')\n" + \
                  "        }\n" + \
                  "    </script>\n" + index_html[insert_index:]
              index_html_file.seek(0)
              index_html_file.truncate()
              index_html_file.write(index_html)

      - name: Pack Artifact
        run: |
          7z a ${{ env.UPLOAD_ARTIFACT_FILEPATH }} ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UPLOAD_ARTIFACT_NAME }}
          path: ${{ env.UPLOAD_ARTIFACT_FILEPATH }}

  deploy-github:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.UPLOAD_ARTIFACT_NAME }}

      - name: Extract Artifact
        working-directory: ${{ github.workspace }}
        run: |
          unzip -q ${{ env.UPLOAD_ARTIFACT_FILEPATH }} -d ./modloader-temp

      - name: Modify manifest.json
        shell: python3 {0}
        run: |
          import json
          
          for manifest_name in ["${{ env.MANIFEST_JSON_NORMAL_FILENAME }}", "${{ env.MANIFEST_JSON_POLYFILL_FILENAME }}"]:
            with open(f"${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/{manifest_name}", "r+", encoding="utf-8") as manifest_file:
              manifest_json = json.loads(manifest_file.read())
              manifest_json["scope"] = "/${{ github.event.repository.name }}/"
              manifest_json["start_url"] = "/${{ github.event.repository.name }}/"
              manifest_json["shortcuts"][0]["url"] = "/${{ github.event.repository.name }}/"
              manifest_json["icons"][0]["src"] = "/${{ github.event.repository.name }}/icon.png"
              manifest_file.seek(0)
              manifest_file.truncate()
              manifest_file.write(json.dumps(manifest_json, indent=2))

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./modloader-temp  # 注意这里只能用相对路径，吐血了差点
          keep_history: false
          target_branch: gh-pages

  post-build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    if: ${{ always() }}

    needs: [build, deploy-github]

    steps:
      - name: Cleanup
        uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ env.UPLOAD_ARTIFACT_NAME }}
